title: Franz Clarence Casaclang
logo: /assets/beach_bust_shot.jpg
description: Registered civil engineer with over a year of experience in structural design, skilled in STAAD Pro, MIDAS Gen, and AutoCAD. Proficient in NSCP 2015 and ACI 318 standards, with a strong background in collaborating with architects and stakeholders. Eager to apply technical expertise to infrastructure and commercial projects.
show_downloads: true
theme: jekyll-theme-minimal
