title: Franz Clarence Casaclang
logo: /assets/beach_bust_shot.jpg
description: 
Graduate of Bachelor of Science in Civil Engineering from Polytechnic University of the Philippines - Sta. Mesa (PUP). I was a Former member of the Philippine Institute of Civil Engineers - PUP Student Chapter (2018-2019). I passed the Civil Engineering Licensure Exam (November 2023) and took my oath to become a Registered Civil Engineer. He continues and pursues to upskill in different engineering softwares used in design (Civil 3D, Staad.Pro, AutoCAD), building information modelling (Revit), and project management (Primavera P6) through online courses and other sources from the internet.
Franz is interested in running small businesses. He established Odyssey Clothing Co. together with 4 of his close friends in 2018, The Flourpuff Co., and All About Aesthetics.

show_downloads: true
theme: jekyll-theme-minimal
